# Generated by Django 5.2 on 2025-05-16 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_ticket_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exhibit',
            options={'verbose_name': 'Экспонат', 'verbose_name_plural': 'Экспонаты'},
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='exhibits/'),
        ),
    ]
